controller_manager:
    ros__parameters:
         update_rate: 1000  # Hz

         use_sim_time: true

         position_controller:
             type: position_controllers/JointGroupPositionController

         joint_state_broadcaster:
             type: joint_state_broadcaster/JointStateBroadcaster

         velocity_controller:
             type: velocity_controllers/JointGroupVelocityController



position_controller:
     ros__parameters:
         joints:
         - joint1
         - joint2
         - joint3
         - joint4
         - joint5
         - joint6
         interface_name: position
         command_interfaces:
         - position
         state_interfaces:
         - position
         - velocity


velocity_controller:
    ros__parameters:
         joints:
         - joint1
         - joint2
         - joint3
         - joint4
         - joint5
         - joint6
         interface_name: velocity
         command_interfaces:
         - velocity
         state_interfaces:
         - position
         - velocity